"""Add multi-stage and secret achievements

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('total_stages', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('achievements', sa.Column('secret', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('achievements', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('achievements', sa.Column('criteria', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.create_foreign_key('fk_achievements_parent_id', 'achievements', 'achievements', ['parent_id'], ['id'])
    
    op.add_column('user_achievements', sa.Column('current_stage', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('user_achievements', 'current_stage')
    
    op.drop_constraint('fk_achievements_parent_id', 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'criteria')
    op.drop_column('achievements', 'parent_id')
    op.drop_column('achievements', 'secret')
    op.drop_column('achievements', 'total_stages')
    # ### end Alembic commands ### 