"""Add daily streaks table

Revision ID: daily_streaks_001
Revises: 1a2b3c4d5e6f
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'daily_streaks_001'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('goal_met', sa.Boolean(), nullable=True),
    sa.Column('total_volume_ml', sa.Float(), nullable=True),
    sa.Column('goal_volume_ml', sa.Float(), nullable=False),
    sa.Column('percentage_completed', sa.Float(), nullable=True),
    sa.Column('streak_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date_streak')
    )
    op.create_index(op.f('ix_daily_streaks_id'), 'daily_streaks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_streaks_id'), table_name='daily_streaks')
    op.drop_table('daily_streaks')
    # ### end Alembic commands ### 